Repository facebookresearch/theseus, pull requests merged in 2021-12, with the labels that each got.

#2 Added clearer explanation at the end of Tutorial 0 and fixed doc typos
  examples/motion_planning_2d.py
  examples/tactile_pose_estimation.py
  tutorials/00_introduction.ipynb
Labels: documentation, CLA Signed

#3 Default SE2/SO2 is zero element rather than torch empty.
  theseus/geometry/se2.py
  theseus/geometry/so2.py
Labels: enhancement, CLA Signed

#25 Add plots to tutorials
  tutorials/01_least_squares_optimization.ipynb
  tutorials/02_differentiable_nlls.ipynb
Labels: documentation, CLA Signed

#31 update text in Tutorial 2 per issue #27
  tutorials/02_differentiating_theseus_layer.ipynb
  tutorials/README.md
Labels: documentation, CLA Signed

#21 update continuous integration
  .circleci/config.yml
Labels: enhancement, CLA Signed

#22 cusolver based batched LU solver
  .circleci/config.yml
  .gitignore
  requirements/main.txt
  setup.py
  theseus/extlib/cusolver_lu_solver.cpp
  theseus/extlib/cusolver_sp_defs.cpp
  theseus/extlib/cusolver_sp_defs.h
  theseus/extlib/tests/test_cusolver_lu_solver.py
  theseus/utils/__init__.py
  theseus/utils/sparse_matrix_utils.py
Labels: enhancement, CLA Signed

#23 CUDA batch matrix multiplication and ops
  .circleci/config.yml
  setup.py
  theseus/extlib/mat_mult.cu
  theseus/extlib/tests/test_mat_mult.py
Labels: enhancement, CLA Signed

#33 Update contrib and add gitattributes
  .gitattributes
  CONTRIBUTING.md
Labels: documentation, CLA Signed

#30 Adds support for energy based learning with NLL loss (LEO)
  examples/state_estimation_2d.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linearization.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
Labels: CLA Signed
