Repository facebookresearch/theseus, pull requests merged in 2022-06, with the labels that each got.

#199 Added aliases for Difference and Between
  examples/bundle_adjustment.py
  examples/pose_graph.py
  examples/se2_inverse.py
  examples/state_estimation_2d.py
  theseus/__init__.py
  theseus/core/tests/test_objective.py
  theseus/embodied/__init__.py
  theseus/embodied/measurements/tests/test_between.py
  theseus/embodied/misc/__init__.py
  theseus/embodied/misc/local_cost_fn.py
  theseus/embodied/misc/tests/test_variable_difference.py
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/utils/examples/motion_planning/motion_planner.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
  tutorials/00_introduction.ipynb
  tutorials/03_custom_cost_functions.ipynb
  tutorials/04_motion_planning.ipynb
Labels: CLA Signed, refactor

#201 Fixed infinite recursion in GPMotionModel.copy()
  theseus/embodied/motionmodel/double_integrator.py
Labels: CLA Signed

#203 Fix bug in diagonal cost weight
  theseus/core/cost_weight.py
  theseus/core/tests/test_cost_weight.py
  theseus/core/tests/test_precision.py
Labels: CLA Signed

#202 Added a check in TheseusFunction that enforces copy() also copies the variables
  theseus/core/tests/common.py
  theseus/core/tests/test_theseus_function.py
  theseus/core/theseus_function.py
Labels: CLA Signed

#204 Fixed bug in Objective.error() that was updating data unncessarily.
  theseus/core/objective.py
Labels: CLA Signed

#161 DLM gradients
  examples/backward_modes.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
  theseus/theseus_layer.py
Labels: enhancement, CLA Signed, experiments

#207 Update README to specify python versions and CUDA during install step +
  .gitignore
  README.md
Labels: CLA Signed

#205 Vectorization refactor
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/cost_function.py
  theseus/core/objective.py
  theseus/core/tests/common.py
  theseus/core/tests/test_objective.py
  theseus/core/tests/test_vectorizer.py
  theseus/core/theseus_function.py
  theseus/core/vectorizer.py
  theseus/embodied/kinematics/tests/test_inverse_kinematics.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linearization.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
  theseus/optimizer/sparse_linearization.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
Labels: enhancement, CLA Signed, refactor

#210 Fixed the rescaling bug for robust cost function
  theseus/core/robust_cost_function.py
Labels: bug, CLA Signed

#148 Implement Robust Cost Function
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/loss.py
  theseus/core/robust_cost_function.py
Labels: enhancement, CLA Signed, experiments, experimental

#212 Added option for auto resetting LUCudaSparseSolver if the batch size needs to change
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
Labels: CLA Signed

#213 Address comments on RobustCostFunction implementation
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/cost_function.py
  theseus/core/loss.py
  theseus/core/robust_cost_function.py
  theseus/core/robust_loss.py
  theseus/core/tests/test_robust_cost.py
Labels: CLA Signed

#214 Moved the method that retracts all variables with a given delta to Objective
  theseus/core/objective.py
  theseus/optimizer/linear/linear_optimizer.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/theseus_layer.py
Labels: CLA Signed

#216 Fixed flaky unit test for Collision2D jacobians.
  theseus/embodied/collision/tests/test_collision_factor.py
Labels: CLA Signed

#149 Bundle Adjustment using RobustCostFunction
  examples/bundle_adjustment.py
  theseus/embodied/__init__.py
  theseus/embodied/measurements/__init__.py
  theseus/embodied/measurements/reprojection.py
  theseus/embodied/measurements/tests/test_reprojection.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/bundle_adjustment/__init__.py
Labels: CLA Signed

#217 Fixed the cross product bug for SE3.exp_map and SE3.log_map
  .gitignore
  theseus/geometry/se3.py
  theseus/geometry/tests/test_se3.py
Labels: bug, CLA Signed

#218 Moved Vectorize(objective) to the Optimizer class.
  theseus/core/objective.py
  theseus/core/tests/test_robust_cost.py
  theseus/core/vectorizer.py
  theseus/embodied/kinematics/tests/test_inverse_kinematics.py
  theseus/optimizer/linear/linear_optimizer.py
  theseus/optimizer/nonlinear/gauss_newton.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_least_squares.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/common.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
  theseus/optimizer/optimizer.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
Labels: CLA Signed

#221 Added on-demand vectorization and also vectorized Objective.error().
  theseus/core/objective.py
  theseus/core/tests/test_vectorizer.py
  theseus/core/variable.py
  theseus/optimizer/linearization.py
Labels: enhancement, CLA Signed

#211 Vectorize PGO
  examples/README.md
  examples/configs/pose_graph/pose_graph_benchmark.yaml
  examples/configs/pose_graph/pose_graph_cube.yaml
  examples/configs/pose_graph/pose_graph_synthetic.yaml
  examples/pose_graph/pose_graph_benchmark.py
  examples/pose_graph/pose_graph_cube.py
  examples/pose_graph/pose_graph_g2o.py
  examples/pose_graph/pose_graph_synthetic.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/pose_graph/__init__.py
  theseus/utils/examples/pose_graph/dataset.py
  theseus/utils/examples/pose_graph/pose_prior_error.py
  theseus/utils/examples/pose_graph/relative_pose_error.py
  theseus/utils/examples/pose_graph/tests/__init__.py
  theseus/utils/examples/pose_graph/tests/test_jacobians.py
Labels: CLA Signed

#222 Destroy cusolver context in CusolverLUSolver destructor
  theseus/extlib/cusolver_lu_solver.cpp
Labels: bug, CLA Signed
