Repository facebookresearch/theseus, pull requests merged in 2022-04, with the labels that each got.

#136 Merge `Between` and `VariableDiff` with `RelativePoseError` and `PosePriorError`
  examples/pose_graph.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  theseus/utils/examples/pose_graph/dataset.py
Labels: CLA Signed

#139 Fix a bug in Objective.copy()
  theseus/core/objective.py
Labels: bug, CLA Signed

#141 Added option to force max iterations for TactilePoseEstimator.
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: CLA Signed

#144 black version bump
  .pre-commit-config.yaml
Labels: CLA Signed

#156 Removed RobotModel.dim()
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/kinematics/robot_model.py
Labels: CLA Signed, refactor

#157 [bug-fix] Fixed wrong data shape initialization for GPCostWeight.dt
  theseus/embodied/motionmodel/double_integrator.py
Labels: bug, CLA Signed

#155 Made AutoDiffCostFunction._tmp_optim_vars copies of original
  theseus/core/cost_function.py
Labels: bug, CLA Signed

#160 All unit tests seems passed for batch processing
  theseus/core/tests/test_objective.py
  theseus/optimizer/tests/linearization_test_utils.py
  theseus/tests/test_theseus_layer.py
Labels: CLA Signed

#84 Add forward kinematics using an URDF to theseus.embodied.kinematics.
  requirements/main.txt
  theseus/embodied/__init__.py
  theseus/embodied/collision/collision.py
  theseus/embodied/kinematics/__init__.py
  theseus/embodied/kinematics/kinematics_model.py
  theseus/embodied/kinematics/robot_model.py
  theseus/embodied/kinematics/tests/data/panda_fk_dataset.json
  theseus/embodied/kinematics/tests/data/panda_no_gripper.urdf
  theseus/embodied/kinematics/tests/test_inverse_kinematics.py
  theseus/embodied/kinematics/tests/test_urdf_model.py
Labels: enhancement, CLA Signed

#162 Tactile pushing example works for batch processing
  examples/pose_graph_synthetic.py
  theseus/core/objective.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: CLA Signed

#158 Fixed dtype error in `se3.py` that came up in unit tests
  theseus/geometry/se3.py
Labels: CLA Signed

#164 Add-ons for backward experiments on Tactile Pose Estimation
  examples/configs/tactile_pose_estimation.yaml
  examples/tactile_pose_estimation.py
  theseus/utils/examples/tactile_pose_estimation/misc.py
  theseus/utils/examples/tactile_pose_estimation/trainer.py
Labels: CLA Signed, experiments

#166 Fix the in-place operation bug
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: bug, CLA Signed

#168 Change unit tests to avoid making mypy a main requirement.
  README.md
  theseus/geometry/tests/test_point_types.py
Labels: bug, documentation, CLA Signed

#169 Update readme and contrib
  CONTRIBUTING.md
  README.md
  THANKS.md
Labels: CLA Signed

#121 Add ManifoldGaussian class for messages in belief propagation
  theseus/__init__.py
  theseus/optimizer/__init__.py
  theseus/optimizer/manifold_gaussian.py
  theseus/optimizer/tests/test_manifold_gaussian.py
Labels: enhancement, CLA Signed

#170 PGO profiling
  examples/configs/pose_graph.yaml
  examples/pose_graph_synthetic.py
  theseus/core/cost_function.py
  theseus/utils/examples/pose_graph/dataset.py
Labels: CLA Signed

#171 Shared aux vars
  theseus/core/objective.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/sparse_linearization.py
  theseus/utils/examples/tactile_pose_estimation/models.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: CLA Signed

#172 Add varying batch size support for LUCudaSparseSolver
  examples/pose_graph_synthetic.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#175 More efficient implementation of forward kinematics
  requirements/main.txt
  theseus/embodied/kinematics/kinematics_model.py
  theseus/embodied/kinematics/tests/test_urdf_model.py
Labels: CLA Signed, performance

#178 Changing setup virtualenv command.
  .circleci/config.yml
Labels: CLA Signed

#177 Updated SDF object in collision cost functions whenever an aux var is updated
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/utils/utils.py
Labels: bug, CLA Signed

#180 Merge latest main to experimental
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  THANKS.md
  requirements/main.txt
  theseus/__init__.py
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/kinematics/kinematics_model.py
  theseus/embodied/kinematics/tests/test_urdf_model.py
  theseus/geometry/tests/test_point_types.py
  theseus/optimizer/__init__.py
  theseus/optimizer/manifold_gaussian.py
  theseus/optimizer/tests/test_manifold_gaussian.py
  theseus/utils/utils.py
Labels: CLA Signed

#181 Fixed device bug that occurred when merging info in TRUNCATED backward modes
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#150 Allow constant inputs to cost functions to be passed as floats
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/collision/tests/test_eff_obj_contact.py
  theseus/embodied/motionmodel/double_integrator.py
  theseus/embodied/motionmodel/tests/test_double_integrator.py
Labels: CLA Signed, refactor
