Repository facebookresearch/theseus, pull requests merged in 2022-08, with the labels that each got.

#264 update readme
  CONTRIBUTING.md
  README.md
Labels: documentation, CLA Signed

#267 Added MotionPlanner.forward() method.
  theseus/__init__.py
  theseus/utils/examples/motion_planning/motion_planner.py
Labels: CLA Signed

#271 Small bug fixes and tweaks to generate_trajectory_figs.
  theseus/utils/examples/motion_planning/misc.py
  tutorials/04_motion_planning.ipynb
  tutorials/05_differentiable_motion_planning.ipynb
Labels: CLA Signed

#257 Added a script for building wheels on a new docker image.
  build_scripts/build_wheel.sh
  docs/source/getting-started.rst
  setup.py
Labels: CLA Signed

#275 Bugfix: homography estimation - create data folder before downloading data
  examples/homography_estimation.py
Labels: CLA Signed

#276 Added pip install theseus-ai instructions.
  README.md
  build_scripts/build_wheel.sh
  docs/source/getting-started.rst
  setup.py
Labels: documentation, CLA Signed

#277 Refactored MotionPlanner so that objective can be passed separately.
  examples/motion_planning_2d.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/motion_planning/__init__.py
  theseus/utils/examples/motion_planning/models.py
  theseus/utils/examples/motion_planning/motion_planner.py
  tutorials/04_motion_planning.ipynb
  tutorials/05_differentiable_motion_planning.ipynb
Labels: CLA Signed

#280 add numel() to Manifold and Lie groups
  theseus/core/tests/common.py
  theseus/core/tests/test_manifold.py
  theseus/geometry/manifold.py
  theseus/optimizer/tests/linearization_test_utils.py
Labels: enhancement, CLA Signed

#278 Add support for SE2 poses in Collision2D
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/collision/tests/test_collision_factor.py
  theseus/embodied/motionmodel/quasi_static_pushing_planar.py
  theseus/geometry/se2.py
  theseus/geometry/tests/test_se2.py
  theseus/utils/examples/tactile_pose_estimation/models.py
Labels: enhancement, CLA Signed
