Repository facebookresearch/theseus, pull requests merged in 2022-09, with the labels that each got.

#266 Refactor SO3 and SE3 to be consistent with functorch
  theseus/geometry/lie_group_check.py
  theseus/geometry/manifold.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so3.py
Labels: enhancement, CLA Signed

#282 Add SE2 support in MotionPlanner
  .pre-commit-config.yaml
  theseus/utils/examples/motion_planning/misc.py
  theseus/utils/examples/motion_planning/motion_planner.py
Labels: enhancement, CLA Signed

#293 Fixed bug in visualization of SE2 motion plans.
  theseus/utils/examples/motion_planning/motion_planner.py
Labels: CLA Signed

#268 Add functorch support for AutoDiffCostFunction
  .circleci/config.yml
  requirements/main.txt
  theseus/core/cost_function.py
  theseus/core/tests/test_cost_function.py
  theseus/geometry/lie_group_check.py
  theseus/geometry/manifold.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
Labels: enhancement, CLA Signed

#294 Changed requirements so that main.txt only includes essential dependencies
  README.md
  docs/source/getting-started.rst
  examples/README.md
  examples/homography_estimation.py
  requirements/dev.txt
  requirements/main.txt
  theseus/embodied/kinematics/kinematics_model.py
  theseus/optimizer/linear_system.py
  theseus/theseus_layer.py
  theseus/utils/examples/tactile_pose_estimation/misc.py
Labels: CLA Signed

#295 Add to_quaternion, rotation, translation and convention comment
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_se3.py
Labels: enhancement, CLA Signed

#299 Added th.as_variable() function to simplify creating new variables.
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/cost_weight.py
  theseus/core/variable.py
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/collision/signed_distance_field.py
  theseus/embodied/motionmodel/double_integrator.py
  theseus/embodied/motionmodel/quasi_static_pushing_planar.py
Labels: enhancement, CLA Signed

#297 Added an optional end-of-step callback to NonlinearOptimizer.optimize().
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/common.py
Labels: enhancement, CLA Signed

#302 Cleanup Baspacho setup
  setup.py
Labels: CLA Signed

#300 Add AutogradMode to AutoDiffCostFunction
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/cost_function.py
  theseus/core/tests/test_cost_function.py
  theseus/geometry/tests/common.py
Labels: CLA Signed

#298 Changed unit tests so that the batch sizes to tests are defined in a central import
  theseus/core/tests/common.py
  theseus/core/tests/test_cost_weight.py
  theseus/core/tests/test_robust_cost.py
  theseus/core/tests/test_vectorizer.py
  theseus/embodied/collision/tests/test_collision_factor.py
  theseus/embodied/collision/tests/test_eff_obj_contact.py
  theseus/embodied/collision/tests/test_signed_distance_field.py
  theseus/embodied/measurements/tests/test_between.py
  theseus/embodied/measurements/tests/test_moving_frame_between.py
  theseus/embodied/misc/tests/test_variable_difference.py
  theseus/embodied/motionmodel/tests/test_double_integrator.py
  theseus/embodied/motionmodel/tests/test_quasi_static_pushing_planar.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_point_types.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/tests/test_vector.py
  theseus/tests/test_dlm_perturbation.py
Labels: CLA Signed

#303 enhance the efficiency of Objectve.add()
  theseus/core/objective.py
Labels: CLA Signed, performance

#307 Added missing end newlines
  evaluations/README.md
  examples/configs/bundle_adjustment.yaml
  requirements/dev.txt
  requirements/docs.txt
  requirements/main.txt
Labels: CLA Signed

#305 Rename BackwardMode.FULL --> UNROLL and simplify backward mode config
  README.md
  examples/backward_modes.py
  examples/bundle_adjustment.py
  examples/homography_estimation.py
  examples/pose_graph/pose_graph_synthetic.py
  examples/simple_example.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
  theseus/tests/test_dlm_perturbation.py
  theseus/theseus_layer.py
  theseus/utils/examples/tactile_pose_estimation/trainer.py
Labels: CLA Signed

#306 Simplified autograd mode specification.
  examples/homography_estimation.py
  theseus/core/cost_function.py
  theseus/core/tests/test_cost_function.py
Labels: CLA Signed

#308 Clean up test_theseus_layer
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/tests/test_theseus_layer.py
Labels: CLA Signed

#309 update readme and bump version
  CITATION.cff
  README.md
  docs/source/img/theseuslayer.png
  examples/simple_example.py
  theseus/__init__.py
Labels: documentation, CLA Signed

#311 Changed homography example to allow benchmarking only cost computation
  examples/configs/homography_estimation.yaml
  examples/homography_estimation.py
Labels: CLA Signed, experiments

#312 Run isort on all files
  theseus/core/cost_function.py
  theseus/core/objective.py
  theseus/core/tests/common.py
  theseus/core/tests/test_cost_weight.py
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/tests/test_collision_factor.py
  theseus/embodied/collision/tests/test_eff_obj_contact.py
  theseus/embodied/collision/tests/test_signed_distance_field.py
  theseus/embodied/collision/tests/utils.py
  theseus/embodied/measurements/tests/test_between.py
  theseus/embodied/measurements/tests/test_moving_frame_between.py
  theseus/embodied/misc/tests/test_variable_difference.py
  theseus/embodied/motionmodel/tests/test_double_integrator.py
  theseus/geometry/manifold.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_point_types.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/tests/test_vector.py
  theseus/optimizer/nonlinear/__init__.py
  theseus/third_party/easyaug.py
Labels: CLA Signed
