Repository facebookresearch/theseus, pull requests merged in 2022-12, with the labels that each got.

#388 Add a workaround for NonlinearOptimizer rejecting all batch steps
  tests/optimizer/nonlinear/test_levenberg_marquardt.py
  tests/test_theseus_layer.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#390 Add code to automatically pick number of LUCuda contexts
  tests/optimizer/linear/test_lu_cuda_sparse_solver.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/linear_solver.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: enhancement, CLA Signed

#396 Bug fix in NonlinearOptimizer.reset() when using LUCudaSparseSolver
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#391 Allow float data to be used with our sparse solver extensions
  tests/optimizer/autograd/common.py
  tests/optimizer/autograd/test_baspacho_sparse_backward.py
  tests/optimizer/autograd/test_lu_cuda_sparse_backward.py
  tests/test_theseus_layer.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/sparse_linearization.py
Labels: enhancement, CLA Signed

#392 Add a differentiable sparse matrix vector product on top of our ops
  tests/optimizer/nonlinear/common.py
  tests/optimizer/test_sparse_linearization.py
  tests/utils/test_utils.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linearization.py
  theseus/optimizer/sparse_linearization.py
  theseus/utils/__init__.py
  theseus/utils/sparse_matrix_utils.py
Labels: enhancement, CLA Signed

#393 Add diagonal scaling method and re-enable LM adaptive + ellipsoidal
  tests/optimizer/nonlinear/common.py
  tests/optimizer/nonlinear/test_levenberg_marquardt.py
  tests/optimizer/test_sparse_linearization.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linearization.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/sparse_linearization.py
Labels: enhancement, CLA Signed

#399 Add a timer util that adapts to a torch.device.
  theseus/utils/__init__.py
  theseus/utils/utils.py
Labels: CLA Signed

#387 Made torch's CUDA_GCC_VERSION check optional in setup.py.
  setup.py
Labels: CLA Signed

#378 Add hat() and vee() operators to theseus.geometry.so3
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed
