Repository facebookresearch/theseus, pull requests merged in 2022-02, with the labels that each got.

#63 Update version
  version.txt
Labels: documentation, CLA Signed

#46 Add SO3 support
  theseus/__init__.py
  theseus/geometry/__init__.py
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#56 Add SO3.to_quaternion
  .pre-commit-config.yaml
  theseus/core/tests/test_objective.py
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
  theseus/utils/examples/motion_planning/models.py
Labels: enhancement, CLA Signed

#65 Taoshaf.add so3 class
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#57 Add SO3 rotate and unrotate
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: enhancement, CLA Signed

#59 add so3._hat_matrix_check()
  theseus/geometry/so3.py
Labels: enhancement, CLA Signed

#52 Added a TactilePoseEstimator class to easily create TheseusLayer for tactile pushing
  examples/tactile_pose_estimation.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/tactile_pose_estimation/__init__.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: CLA Signed, experiments, refactor

#55 Refactor tactile pushing model interface
  examples/tactile_pose_estimation.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/tactile_pose_estimation/__init__.py
  theseus/utils/examples/tactile_pose_estimation/models.py
Labels: CLA Signed, experiments, refactor

#66 Minor fixes 02/01/2022
  setup.cfg
  theseus/core/cost_function.py
  theseus/core/tests/test_cost_function.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#68 add adjoint, hat and vee for SE3
  theseus/__init__.py
  theseus/geometry/__init__.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so3.py
Labels: enhancement, CLA Signed

#71 Add SE3.exp_map() and SE3.log_map()
  theseus/geometry/se3.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so3.py
Labels: enhancement, CLA Signed

#72 Add SE3.compose()
  theseus/geometry/se3.py
  theseus/geometry/tests/test_se3.py
Labels: enhancement, CLA Signed

#80 add SE3.transform_from and SE3.transform_to
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_se3.py
Labels: CLA Signed

#90 Updated README with libsuitesparse installation instructions.
  README.md
Labels: documentation, CLA Signed

#82 Added kwarg to NonlinearOptimizer.optimizer() for tracking error history
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/common.py
Labels: enhancement, CLA Signed

#83 Merge infos results for truncated backward modes
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#75 Add Lie Group Support to PyTorch Optimizers
  examples/se2_inverse.py
  theseus/__init__.py
  theseus/geometry/__init__.py
  theseus/geometry/utils.py
Labels: enhancement, CLA Signed
