Repository facebookresearch/theseus, pull requests merged in 2022-01, with the labels that each got.

#29 Initial implicit/truncated backward modes
  examples/README.md
  examples/backward_modes.py
  requirements/main.txt
  theseus/__init__.py
  theseus/optimizer/nonlinear/__init__.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
Labels: CLA Signed

#45 Changed TheseusLayer.forward() to receive optimizer_kwargs as a single dict
  .pre-commit-config.yaml
  examples/backward_modes.py
  examples/motion_planning_2d.py
  examples/state_estimation_2d.py
  examples/tactile_pose_estimation.py
  requirements/dev.txt
  requirements/main.txt
  theseus/core/objective.py
  theseus/optimizer/nonlinear/tests/test_backwards.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
  tutorials/01_least_squares_optimization.ipynb
  tutorials/02_differentiating_theseus_layer.ipynb
  tutorials/04_motion_planning.ipynb
  tutorials/05_differentiable_motion_planning.ipynb
Labels: CLA Signed, refactor

#49 Taoshaf.check se2
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#48 Add SO3.exp_map() and SO3.log_map()
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#47 add SO3.hat() and SO3.vee()
  theseus/geometry/se2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#24 CUDA-based solver class and autograd function
  .circleci/config.yml
  README.md
  theseus/__init__.py
  theseus/extlib/tests/test_cusolver_lu_solver.py
  theseus/extlib/tests/test_mat_mult.py
  theseus/optimizer/autograd/__init__.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/autograd/tests/test_lu_cuda_sparse_backward.py
  theseus/optimizer/linear/__init__.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/linear/tests/test_lu_cuda_sparse_solver.py
  theseus/optimizer/linear_system.py
Labels: enhancement, CLA Signed

#54 [hotfix] fix lint issues
  theseus/core/tests/test_objective.py
  theseus/geometry/se2.py
  theseus/utils/examples/motion_planning/models.py
Labels: CLA Signed
