Repository facebookresearch/theseus, pull requests merged in 2022-11, with the labels that each got.

#345 Change CI to separately handle torch >= 1.13
  .circleci/config.yml
  build_scripts/build_wheel.sh
  requirements/main.txt
Labels: CLA Signed

#344 Fixed quaternion bug at pi
  theseus/geometry/so3.py
Labels: bug, CLA Signed

#335 Expose Lie Groups checks at root level
  theseus/__init__.py
  theseus/geometry/__init__.py
Labels: CLA Signed

#328 Adaptive damping for Levenberg-Marquardt
  theseus/extlib/baspacho_solver.cpp
  theseus/extlib/baspacho_solver.h
  theseus/extlib/baspacho_solver_cuda.cu
  theseus/extlib/mat_mult.cu
  theseus/extlib/tests/test_baspacho.py
  theseus/extlib/tests/test_cusolver_lu_solver.py
  theseus/extlib/tests/test_mat_mult.py
  theseus/extlib/utils.h
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/autograd/tests/__init__.py
  theseus/optimizer/autograd/tests/test_baspacho_sparse_backward.py
  theseus/optimizer/autograd/tests/test_lu_cuda_sparse_backward.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/cholmod_sparse_solver.py
  theseus/optimizer/linear/dense_solver.py
  theseus/optimizer/linear/linear_solver.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/linear/tests/test_baspacho_sparse_solver.py
  theseus/optimizer/linear/tests/test_dense_solver.py
  theseus/optimizer/linear/tests/test_lu_cuda_sparse_solver.py
  theseus/optimizer/linear/utils.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/utils/sparse_matrix_utils.py
Labels: enhancement, CLA Signed

#351 Added option for making LieGroup checks silent.
  theseus/core/cost_function.py
  theseus/geometry/lie_group_check.py
  theseus/geometry/manifold.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so3.py
Labels: CLA Signed

#349 Added a few other CUDA versions to build script.
  build_scripts/build_wheel.sh
Labels: CLA Signed

#350 Set vectorization off by default when using optimizers w/o TheseusLayer
  README.md
  theseus/constants.py
  theseus/optimizer/linear/linear_optimizer.py
  theseus/optimizer/nonlinear/gauss_newton.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_least_squares.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_gauss_newton.py
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/optimizer/nonlinear/tests/test_state_history.py
  theseus/optimizer/optimizer.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
  tutorials/00_introduction.ipynb
Labels: CLA Signed

#353 Some more cleanup before 0.1.3
  examples/README.md
  examples/backward_modes.py
  requirements/dev.txt
  requirements/docs.txt
  tests/core/test_cost_weight.py
  tests/core/test_vectorizer.py
  tests/embodied/collision/sdf_data.csv
  tests/embodied/collision/test_eff_obj_contact.py
  tests/embodied/measurements/between_errors_se2.npy
  tests/embodied/measurements/between_errors_so2.npy
  tests/embodied/measurements/test_between.py
  tests/embodied/misc/sq_dist_errors_se2.npy
  tests/embodied/misc/sq_dist_errors_so2.npy
  tests/embodied/misc/test_variable_difference.py
  tests/optimizer/nonlinear/test_backwards.py
  tests/test_dlm_perturbation.py
  tests/test_theseus_layer.py
  theseus/theseus_layer.py
Labels: CLA Signed

#354 Add tests for wheels in CI
  .circleci/config.yml
  build_scripts/build_wheel.sh
  tests/__init__.py
Labels: CLA Signed

#356 #355 Add device parameter to UrdfRobotModel
  tests/embodied/kinematics/test_urdf_model.py
  theseus/embodied/kinematics/kinematics_model.py
Labels: CLA Signed, refactor

#357 Added th.device to represent both str and torch.device.
  MANIFEST.in
  theseus/__init__.py
  theseus/constants.py
  theseus/core/objective.py
  theseus/core/variable.py
  theseus/embodied/kinematics/kinematics_model.py
  theseus/geometry/lie_group.py
  theseus/geometry/point_types.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/vector.py
  theseus/optimizer/linear/utils.py
  theseus/py.typed
  theseus/theseus_layer.py
  theseus/utils/examples/motion_planning/motion_planner.py
  theseus/utils/examples/pose_graph/dataset.py
  theseus/utils/examples/tactile_pose_estimation/misc.py
  theseus/utils/examples/tactile_pose_estimation/models.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
  theseus/utils/examples/tactile_pose_estimation/trainer.py
Labels: CLA Signed

#358 Update to 0.1.3
  theseus/__init__.py
Labels: CLA Signed

#362 Minor vmap fix in SO2
  theseus/geometry/so2.py
Labels: CLA Signed

#360 Add sparse solvers support to LM adaptive damping
  examples/configs/pose_graph/pose_graph_synthetic.yaml
  examples/pose_graph/pose_graph_synthetic.py
  tests/optimizer/linear/test_dense_solver.py
  tests/optimizer/nonlinear/common.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linearization.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/sparse_linearization.py
  theseus/utils/__init__.py
  theseus/utils/sparse_matrix_utils.py
Labels: CLA Signed

#365 Add theseus.geometry.functional.so3 module with exp() and jexp() implementations
  tests/geometry/functional/__init__.py
  tests/geometry/functional/common.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/__init__.py
  theseus/geometry/functional/__init__.py
  theseus/geometry/functional/constants.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/so3.py
  theseus/geometry/functional/utils.py
Labels: enhancement, CLA Signed

#363 Change Objective.error() so it can be vectorized w/o changing vectorized cache
  tests/core/test_vectorizer.py
  tests/test_theseus_layer.py
  theseus/core/objective.py
  theseus/core/vectorizer.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/sparse_linearization.py
Labels: bug, CLA Signed

#372 Added missing square in `test_theseus_layer` loss.
  tests/optimizer/nonlinear/test_levenberg_marquardt.py
  tests/test_theseus_layer.py
  theseus/optimizer/linear/dense_solver.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
Labels: CLA Signed

#373 Add theseus.geometry.functional.so3.adjoint()
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#374 Add theseus.geometry.functional.so3.inverse()
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#364 Add proper accept/reject logic for LM optimizer
  theseus/core/objective.py
  theseus/optimizer/linear/linear_optimizer.py
  theseus/optimizer/nonlinear/gauss_newton.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/theseus_layer.py
Labels: enhancement, CLA Signed

#386 Cleaned up sparse solvers code
  tests/extlib/test_baspacho.py
  tests/extlib/test_cusolver_lu_solver.py
  tests/extlib/test_mat_mult.py
  tests/optimizer/autograd/test_baspacho_sparse_backward.py
  tests/optimizer/autograd/test_lu_cuda_sparse_backward.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/cholmod_sparse_autograd.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/linear_system.py
  theseus/optimizer/sparse_linearization.py
  theseus/utils/__init__.py
  theseus/utils/sparse_matrix_utils.py
Labels: CLA Signed

#389 Remove softmax from end to end test and do some clean up
  tests/test_theseus_layer.py
Labels: CLA Signed
