Repository facebookresearch/theseus, pull requests merged in 2022-07, with the labels that each got.

#226 Vectorization handles singleton costs
  theseus/core/tests/test_vectorizer.py
  theseus/core/vectorizer.py
  theseus/tests/test_theseus_layer.py
Labels: enhancement, CLA Signed, performance

#224 Added close-formed jacobian for DLM perturbation cost.
  theseus/tests/test_dlm_perturbation.py
  theseus/theseus_layer.py
Labels: CLA Signed

#220 SE2/SE3/SO3 - consolidate EPS, add dtype-conditioned EPS and add float32 unit tests
  theseus/constants.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/optimizer/tests/test_manifold_gaussian.py
Labels: CLA Signed

#227 Add normalization to Lie group
  theseus/constants.py
  theseus/geometry/manifold.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/vector.py
Labels: enhancement, CLA Signed

#230 More data -> tensor renaming
  examples/bundle_adjustment.py
  examples/pose_graph/pose_graph_cube.py
  examples/pose_graph/pose_graph_synthetic.py
  theseus/core/objective.py
  theseus/core/tests/common.py
  theseus/core/tests/test_manifold.py
  theseus/core/tests/test_objective.py
  theseus/core/vectorizer.py
  theseus/geometry/lie_group.py
  theseus/geometry/manifold.py
  theseus/geometry/point_types.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/vector.py
  theseus/optimizer/tests/linearization_test_utils.py
  theseus/tests/test_theseus_layer.py
  theseus/theseus_layer.py
Labels: CLA Signed, refactor

#234 Added state history tracking
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: CLA Signed

#235 Unified all cost functions so that cost weight is the last non-default argument
  examples/bundle_adjustment.py
  examples/pose_graph/pose_graph_benchmark.py
  examples/pose_graph/pose_graph_cube.py
  examples/pose_graph/pose_graph_g2o.py
  examples/pose_graph/pose_graph_synthetic.py
  examples/se2_inverse.py
  examples/state_estimation_2d.py
  theseus/core/cost_function.py
  theseus/core/tests/test_cost_weight.py
  theseus/core/tests/test_objective.py
  theseus/core/tests/test_robust_cost.py
  theseus/core/tests/test_vectorizer.py
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/collision/tests/test_collision_factor.py
  theseus/embodied/collision/tests/test_eff_obj_contact.py
  theseus/embodied/measurements/between.py
  theseus/embodied/measurements/moving_frame_between.py
  theseus/embodied/measurements/tests/test_between.py
  theseus/embodied/measurements/tests/test_moving_frame_between.py
  theseus/embodied/misc/local_cost_fn.py
  theseus/embodied/misc/tests/test_variable_difference.py
  theseus/embodied/motionmodel/quasi_static_pushing_planar.py
  theseus/embodied/motionmodel/tests/test_quasi_static_pushing_planar.py
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/tests/test_dlm_perturbation.py
  theseus/utils/examples/motion_planning/motion_planner.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
  tutorials/00_introduction.ipynb
  tutorials/04_motion_planning.ipynb
Labels: CLA Signed, refactor

#237 Add sphinx and readthedocs configuration
  .readthedocs.yaml
  docs/source/conf.py
  docs/source/core.rst
  docs/source/embodied.rst
  docs/source/generated/theseus.Objective.rst
  docs/source/generated/theseus.Variable.rst
  docs/source/geometry.rst
  docs/source/getting-started.rst
  docs/source/index.rst
  docs/source/optimizer.rst
  docs/source/utils.rst
  requirements/dev.txt
  requirements/docs.txt
  theseus/core/objective.py
  theseus/core/variable.py
Labels: documentation, CLA Signed

#240 Fixed bug in state history for matrix data tensors.
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/tests/test_state_history.py
Labels: bug, CLA Signed

#243 Added isort for examples folder
  .pre-commit-config.yaml
  examples/backward_modes.py
  examples/bundle_adjustment.py
  examples/motion_planning_2d.py
  examples/pose_graph/pose_graph_benchmark.py
  examples/pose_graph/pose_graph_cube.py
  examples/pose_graph/pose_graph_g2o.py
  examples/pose_graph/pose_graph_synthetic.py
  examples/se2_inverse.py
  examples/state_estimation_2d.py
  examples/tactile_pose_estimation.py
Labels: CLA Signed

#246 Avoid batching SDF data, since it's shared by all trajectories.
  theseus/utils/examples/tactile_pose_estimation/models.py
Labels: CLA Signed

#247 Fixed device bug in DLM perturbation's jacobians
  theseus/theseus_layer.py
Labels: CLA Signed

#244 Benchmark PGO on the main branch
  examples/configs/pose_graph/pose_graph_benchmark.yaml
  examples/configs/pose_graph/pose_graph_cube.yaml
  examples/pose_graph/pose_graph_benchmark.py
  examples/pose_graph/pose_graph_cube.py
Labels: CLA Signed

#245 Added checks to enforce 32- or 64-bit dtype
  theseus/constants.py
  theseus/core/tests/test_objective.py
  theseus/geometry/manifold.py
Labels: CLA Signed

#251 Update readme
  README.md
  docs/source/img/theseuslayer.png
Labels: documentation, CLA Signed

#252 Added MANIFEST.in and changed project name to theseus-ai.
  .gitignore
  MANIFEST.in
  setup.py
Labels: CLA Signed

#249 Added option to clear cuda cache when vectorization cache is cleared.
  examples/configs/pose_graph/pose_graph_synthetic.yaml
  examples/pose_graph/pose_graph_synthetic.py
  theseus/core/vectorizer.py
  theseus/optimizer/linear/linear_optimizer.py
  theseus/optimizer/nonlinear/gauss_newton.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/nonlinear_least_squares.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/optimizer.py
  theseus/theseus_layer.py
Labels: CLA Signed

#241 Added evaluation directory
  evaluations/README.md
  evaluations/backward_modes_tactile.sh
  evaluations/pose_graph_cube.sh
  evaluations/pose_graph_synthetic.sh
  evaluations/vectorization_ablation.sh
  examples/README.md
  examples/configs/tactile_pose_estimation.yaml
  examples/pose_graph/pose_graph_cube.py
  examples/pose_graph/pose_graph_g2o.py
  theseus/utils/examples/tactile_pose_estimation/trainer.py
Labels: CLA Signed

#256 update pose graph data link
  examples/pose_graph/pose_graph_benchmark.py
  examples/pose_graph/pose_graph_cube.py
Labels: CLA Signed

#258 [homography] Use kornia lib properly for perspective transform
  examples/homography_estimation.py
  theseus/third_party/easyaug.py
Labels: CLA Signed, refactor

#259 Small Update to 00_introduction.ipynb
  tutorials/00_introduction.ipynb
Labels: CLA Signed

#260 Changed SDF constructor to accept more convenient data types.
  examples/motion_planning_2d.py
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/collision/signed_distance_field.py
  theseus/embodied/collision/tests/__init__.py
  theseus/embodied/collision/tests/test_collision_factor.py
  theseus/embodied/collision/tests/test_eff_obj_contact.py
  theseus/embodied/collision/tests/test_signed_distance_field.py
  theseus/embodied/collision/tests/utils.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
  tutorials/04_motion_planning.ipynb
  tutorials/05_differentiable_motion_planning.ipynb
Labels: enhancement, CLA Signed

#263 Added option to visualize SDF to trajectory visualization function
  theseus/utils/examples/motion_planning/misc.py
Labels: CLA Signed
