Repository facebookresearch/theseus, pull requests merged in 2022-03, with the labels that each got.

#97 Fix Issue 88
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
Labels: CLA Signed

#96 Fixed bug in Variable.update() that was breaking torch graph...
  theseus/core/variable.py
Labels: bug, CLA Signed

#81 Forced Gauss-Newton step for last iterations of truncated backward.
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#74 Add automatic differentiation on the Lie group tangent space
  examples/README.md
  examples/se2_inverse.py
  theseus/__init__.py
  theseus/geometry/__init__.py
  theseus/geometry/lie_group.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/utils.py
  theseus/geometry/vector.py
Labels: enhancement, CLA Signed

#95 Add rand() to LieGroup
  theseus/__init__.py
  theseus/constants.py
  theseus/geometry/__init__.py
  theseus/geometry/lie_group.py
  theseus/geometry/point_types.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/vector.py
Labels: CLA Signed, refactor

#58 Fix SO2 rotate and unrotate jacobian
  theseus/geometry/so2.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/utils/utils.py
Labels: bug, CLA Signed

#98 Add projection for sparse Jacobian matrices
  .gitignore
  theseus/core/tests/common.py
  theseus/core/tests/test_manifold.py
  theseus/geometry/lie_group.py
  theseus/geometry/manifold.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/vector.py
  theseus/optimizer/tests/linearization_test_utils.py
Labels: enhancement, CLA Signed, refactor

#87 Enabled back ellipsoidal damping in LM with linear solvers support checks
  noxfile.py
  theseus/core/objective.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/nonlinear/levenberg_marquardt.py
  theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
  theseus/optimizer/sparse_linearization.py
Labels: CLA Signed

#102 Changed name of pytest mark for CUDA extensions.
  .circleci/config.yml
  README.md
  setup.cfg
  theseus/extlib/tests/test_cusolver_lu_solver.py
  theseus/extlib/tests/test_mat_mult.py
  theseus/optimizer/autograd/tests/test_lu_cuda_sparse_backward.py
  theseus/optimizer/linear/tests/test_lu_cuda_sparse_solver.py
Labels: CLA Signed

#109 Fix backpropagation bugs in SO3 and SE3 log_map
  theseus/geometry/se3.py
  theseus/geometry/so3.py
Labels: bug, CLA Signed

#110 Add analytical jacobians for `LieGroup.exp_map`
  theseus/geometry/lie_group.py
  theseus/geometry/point_types.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_point_types.py
  theseus/geometry/tests/test_se2.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/tests/test_vector.py
  theseus/geometry/vector.py
Labels: enhancement, CLA Signed

#105 error and errorsquaredNorm optional data
  theseus/core/objective.py
  theseus/core/tests/test_objective.py
Labels: enhancement, CLA Signed

#114 Add analytical derivatives for `LieGroup.log_map()`
  .gitignore
  theseus/geometry/lie_group.py
  theseus/geometry/point_types.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_point_types.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/tests/test_vector.py
  theseus/geometry/vector.py
Labels: enhancement, CLA Signed

#94 Change RobotModel.forward_kinematics() interface
  theseus/embodied/collision/collision.py
  theseus/embodied/collision/eff_obj_contact.py
  theseus/embodied/kinematics/robot_model.py
Labels: CLA Signed, refactor

#119 Added error handling for missing `matplotlib` and `omegaconf` installation when using `theg`
  theseus/utils/examples/__init__.py
Labels: CLA Signed

#122 Add jacobians argument to exp_map and log_map functions
  theseus/geometry/lie_group.py
Labels: CLA Signed, refactor

#118 Add pose graph optimization example
  .gitignore
  examples/pose_graph.py
  theseus/utils/examples/__init__.py
  theseus/utils/examples/pose_graph/__init__.py
  theseus/utils/examples/pose_graph/dataset.py
  theseus/utils/examples/pose_graph/pose_prior_error.py
  theseus/utils/examples/pose_graph/relative_pose_error.py
  theseus/utils/examples/pose_graph/tests/__init__.py
  theseus/utils/examples/pose_graph/tests/test_jacobians.py
Labels: enhancement, CLA Signed, experiments

#129 Add jacobians for `LieGroup.local()`
  theseus/geometry/lie_group.py
  theseus/geometry/manifold.py
  theseus/geometry/so2.py
  theseus/geometry/tests/common.py
  theseus/geometry/tests/test_point_types.py
  theseus/geometry/tests/test_se3.py
  theseus/geometry/tests/test_so2.py
  theseus/geometry/tests/test_so3.py
  theseus/geometry/tests/test_vector.py
  theseus/geometry/vector.py
Labels: CLA Signed

#131 Added method to update SE2 from x_y_theta.
  theseus/geometry/se2.py
Labels: CLA Signed

#117 A complete version of Bundle Adjusment
  examples/bundle_adjustment.py
  examples/configs/bundle_adjustment.yaml
  theseus/utils/examples/__init__.py
  theseus/utils/examples/bundle_adjustment/__init__.py
  theseus/utils/examples/bundle_adjustment/data.py
  theseus/utils/examples/bundle_adjustment/reprojection_error.py
  theseus/utils/examples/bundle_adjustment/tests/test_reprojection_error.py
  theseus/utils/examples/bundle_adjustment/util.py
Labels: CLA Signed, experiments

#132 Added batching support to tactile pushing example.
  examples/configs/tactile_pose_estimation.yaml
  examples/tactile_pose_estimation.py
  theseus/utils/examples/tactile_pose_estimation/misc.py
  theseus/utils/examples/tactile_pose_estimation/models.py
  theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
Labels: enhancement, CLA Signed

#137 Changed tactile pose example optim var initialization to use start pose for all vars
  examples/configs/tactile_pose_estimation.yaml
  examples/tactile_pose_estimation.py
  theseus/utils/examples/tactile_pose_estimation/models.py
Labels: CLA Signed, experiments

#124 Override Vector operators in Point2 and Point3
  .circleci/config.yml
  theseus/geometry/point_types.py
  theseus/geometry/tests/point_types_mypy_check.py
  theseus/geometry/tests/test_point_types.py
Labels: CLA Signed
