Repository facebookresearch/theseus, pull requests merged in 2023-05, with the labels that each got.

#504 Add `labs.lie` support for `functorch` and `vmap` pt. 1
  tests/labs/lie/functional/common.py
  tests/labs/lie/functional/test_se3.py
  tests/labs/lie/functional/test_so3.py
  theseus/labs/lie/functional/__init__.py
  theseus/labs/lie/functional/check_contexts.py
  theseus/labs/lie/functional/lie_group.py
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
  theseus/labs/lie/lie_tensor.py
Labels: CLA Signed

#510 Fixed convergence check error in DCEM with negative error metrics.
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: CLA Signed

#508 Update checks to be consistent with multi-batch implementation
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
  theseus/labs/lie/functional/utils.py
Labels: CLA Signed, refactor

#512 Add multi-batch support for SE(3) unary operators
  theseus/labs/lie/functional/constants.py
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
Labels: enhancement, CLA Signed

#503 Added an option to flatten_dims in RobustCostFunction.
  tests/core/test_robust_cost.py
  theseus/core/robust_cost_function.py
  theseus/core/vectorizer.py
Labels: CLA Signed

#513 Add multi-batch compose() and transform_from() for SO(3) and SE(3)
  tests/labs/lie/functional/common.py
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
  theseus/labs/lie/functional/utils.py
Labels: enhancement, CLA Signed

#515 Implemented multi-batch gradient ops
  tests/labs/lie/functional/common.py
  theseus/labs/lie/functional/lie_group.py
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
  theseus/labs/lie/functional/utils.py
Labels: enhancement, CLA Signed

#518 Update pre-commit versions and skip failing mypy import tests.
  .pre-commit-config.yaml
  setup.cfg
Labels: CLA Signed
