Repository facebookresearch/theseus, pull requests merged in 2023-06, with the labels that each got.

#522 Multi-batch unit tests for Lie groups
  tests/labs/lie/functional/common.py
  tests/labs/lie/functional/test_se3.py
  tests/labs/lie/functional/test_so3.py
  theseus/labs/lie/functional/se3_impl.py
  theseus/labs/lie/functional/so3_impl.py
Labels: CLA Signed

#525 Deprecated torch < 2.0.0.
  .circleci/config.yml
  build_scripts/build_wheel.sh
  requirements/main.txt
  setup.py
  theseus/__init__.py
  theseus/_version.py
  theseus/core/cost_function.py
Labels: CLA Signed

#539 Migrate SO3 (reissue)
  tests/theseus_tests/core/test_vectorizer.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
Labels: CLA Signed

#526 Migrate SE3 backend to `torchlie`
  tests/theseus_tests/test_pgo_benchmark.py
  theseus/geometry/se3.py
Labels: CLA Signed

#528 Added configurable global options for `torchlie` and `theseus`
  lie/lie/__init__.py
  lie/lie/functional/constants.py
  lie/lie/functional/se3_impl.py
  lie/lie/functional/so3_impl.py
  lie/lie/options.py
  tests/lie_tests/test_misc.py
  theseus/constants.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/options.py
Labels: CLA Signed

#532 Add other autograd options for `AutoDiffCostFunction`
  theseus/core/cost_function.py
Labels: CLA Signed

#533 Fix package info for building wheel
  build_scripts/build_wheel.sh
  setup.py
  theseus/labs/embodied/__init__.py
  theseus/labs/embodied/robot/__init__.py
Labels: CLA Signed

#541 Fix SO3 rotate check
  theseus/geometry/so3.py
Labels: CLA Signed

#540 Add `kwarg` to disable manifold checks in constructor
  tests/theseus_tests/core/test_vectorizer.py
  theseus/geometry/lie_group.py
  theseus/geometry/manifold.py
  theseus/geometry/se2.py
  theseus/geometry/se3.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/utils/examples/pose_graph/dataset.py
Labels: CLA Signed

#543 Refactored FK to support vmap and other staff
  lie/lie/lie_tensor.py
  tests/labs/embodied/robot/test_forward_kinematics.py
  theseus/labs/embodied/robot/forward_kinematics.py
  theseus/labs/embodied/robot/robot.py
Labels: CLA Signed

#544 Add extra eps for dlog
  lie/lie/functional/se3_impl.py
  lie/lie/functional/so3_impl.py
  lie/lie/options.py
Labels: CLA Signed

#546 Fix a bug un precommit that was preventing `isort` and `black` from being run
  .pre-commit-config.yaml
  theseus/_version.py
  theseus/constants.py
  theseus/core/variable.py
  theseus/geometry/point_types.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  theseus/labs/embodied/robot/forward_kinematics.py
  theseus/labs/embodied/robot/joint.py
  theseus/labs/embodied/robot/robot.py
  theseus/optimizer/autograd/__init__.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/cholmod_sparse_autograd.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/linear/__init__.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/utils.py
  theseus/optimizer/nonlinear/dcem.py
  theseus/optimizer/nonlinear/nonlinear_least_squares.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/nonlinear/trust_region.py
  theseus/optimizer/sparse_linearization.py
  theseus/options.py
  theseus/theseus_layer.py
  theseus/third_party/lml.py
  theseus/utils/__init__.py
  torchlie/torchlie/__init__.py
  torchlie/torchlie/functional/constants.py
  torchlie/torchlie/functional/lie_group.py
  torchlie/torchlie/functional/se3_impl.py
  torchlie/torchlie/functional/so3_impl.py
  torchlie/torchlie/functional/utils.py
  torchlie/torchlie/lie_tensor.py
  torchlie/torchlie/options.py
  torchlie/torchlie/types.py
Labels: CLA Signed

#547 Rename GlobalOptions as Params and remove duplication of some of them with `torchlie`
  tests/torchlie_tests/test_misc.py
  theseus/__init__.py
  theseus/_version.py
  theseus/geometry/se2.py
  theseus/geometry/so2.py
  theseus/geometry/so3.py
  theseus/global_params.py
  torchlie/torchlie/__init__.py
  torchlie/torchlie/functional/se3_impl.py
  torchlie/torchlie/functional/so3_impl.py
  torchlie/torchlie/global_params.py
Labels: CLA Signed

#548 Removed Objective.error_squared_norm()
  theseus/core/objective.py
Labels: CLA Signed

#549 Add README for torchlie
  torchlie/README.md
Labels: CLA Signed

#550 Graduate FK code out of `labs`
  .circleci/config.yml
  .pre-commit-config.yaml
  requirements/dev.txt
  requirements/main.txt
  tests/theseus_tests/embodied/kinematics/test_inverse_kinematics.py
  tests/theseus_tests/embodied/kinematics/test_urdf_model.py
  tests/torchkin_tests/panda_fk_dataset.json
  tests/torchkin_tests/panda_no_gripper.urdf
  tests/torchkin_tests/test_forward_kinematics.py
  theseus/embodied/kinematics/kinematics_model.py
  theseus/labs/embodied/robot/__init__.py
  torchkin/LICENSE
  torchkin/MANIFEST.in
  torchkin/README.md
  torchkin/requirements.txt
  torchkin/setup.py
  torchkin/torchkin/__init__.py
  torchkin/torchkin/forward_kinematics.py
  torchkin/torchkin/joint.py
  torchkin/torchkin/py.typed
  torchkin/torchkin/robot.py
  torchlie/torchlie/__init__.py
Labels: CLA Signed

#551 transform_from -> transform
  tests/torchlie_tests/functional/common.py
  tests/torchlie_tests/functional/test_se3.py
  tests/torchlie_tests/functional/test_so3.py
  tests/torchlie_tests/test_lie_tensor.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  torchlie/torchlie/__init__.py
  torchlie/torchlie/functional/lie_group.py
  torchlie/torchlie/functional/se3_impl.py
  torchlie/torchlie/functional/so3_impl.py
  torchlie/torchlie/lie_tensor.py
Labels: CLA Signed

#552 Add untransform
  tests/torchlie_tests/functional/common.py
  tests/torchlie_tests/functional/test_se3.py
  tests/torchlie_tests/functional/test_so3.py
  tests/torchlie_tests/test_lie_tensor.py
  theseus/geometry/se3.py
  theseus/geometry/so3.py
  torchlie/torchlie/__init__.py
  torchlie/torchlie/functional/lie_group.py
  torchlie/torchlie/functional/se3_impl.py
  torchlie/torchlie/functional/so3_impl.py
  torchlie/torchlie/lie_tensor.py
Labels: CLA Signed

#553 Add `d_near_zero` to `SE2`
  theseus/geometry/se2.py
  theseus/global_params.py
Labels: bug, CLA Signed

#557 update torchlie readme
  torchlie/README.md
Labels: documentation, CLA Signed

#558 update theseus readme
  README.md
Labels: documentation, CLA Signed

#559 Add torchkin example
  torchkin/README.md
Labels: enhancement, CLA Signed
