Repository facebookresearch/theseus, pull requests merged in 2023-01, with the labels that each got.

#400 Fix bug in Vectorization of autodiff costs.
  tests/core/test_vectorizer.py
  theseus/core/vectorizer.py
Labels: bug, CLA Signed

#401 Objective.error() no longer updates vectorization if also_update=False.
  theseus/core/objective.py
Labels: enhancement, CLA Signed

#414 Add se3.log()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#413 Add se3.left_project()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#412 Add se3.left_act()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#411 Add se3.lift() and se3.project()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#410 Add se3.compose()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#409 Add se3.hat() and se3.vee()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#408 Add se3.inverse()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#407 Add se3.adjoint()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: CLA Signed

#406 Add se3.exp()
  tests/geometry/functional/test_se3.py
  theseus/geometry/functional/se3.py
Labels: enhancement, CLA Signed

#404 Add so3.log()
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: CLA Signed

#385 Add left_project() to theseus.geometry.functional.so3
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#383 Add left_act() to theseus.geometry.functional.so3
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#382 Add lift() and project() to theseus.geometry.functional.so3
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#381 Add rand() and randn() to theseus.geometry.functional.so3
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#380 Add quaternion_to_rotation() to theseus.geometry.functional.so3
  tests/geometry/functional/common.py
  tests/geometry/functional/test_se3.py
  tests/geometry/functional/test_so3.py
  theseus/geometry/functional/lie_group.py
  theseus/geometry/functional/se3.py
  theseus/geometry/functional/so3.py
Labels: enhancement, CLA Signed

#398 Add support for masking jacobians of zero weights in the batch
  tests/core/common.py
  tests/core/test_robust_cost.py
  tests/core/test_vectorizer.py
  tests/embodied/motionmodel/test_double_integrator.py
  tests/optimizer/linearization_test_utils.py
  theseus/__init__.py
  theseus/core/__init__.py
  theseus/core/cost_function.py
  theseus/core/cost_weight.py
  theseus/core/robust_cost_function.py
  theseus/core/variable.py
  theseus/core/vectorizer.py
  theseus/embodied/motionmodel/double_integrator.py
Labels: enhancement, CLA Signed

#428 update flake8 to github
  .pre-commit-config.yaml
Labels: CLA Signed

#431 Use IMPLICIT for test_theseus_layer and fix related bugs
  tests/test_theseus_layer.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
Labels: bug, CLA Signed

#424 Add a `labs` package for experimental stuff
  README.md
  build_scripts/build_wheel.sh
  docs/source/getting-started.rst
  setup.py
  tests/decorators.py
  tests/extlib/common.py
  tests/extlib/test_baspacho.py
  tests/extlib/test_baspacho_simple.py
  tests/labs/lie_functional/__init__.py
  tests/labs/lie_functional/common.py
  tests/labs/lie_functional/test_so3.py
  tests/optimizer/autograd/test_baspacho_sparse_backward.py
  tests/optimizer/linear/test_baspacho_sparse_solver.py
  theseus/geometry/__init__.py
  theseus/labs/__init__.py
  theseus/labs/lie_functional/__init__.py
  theseus/labs/lie_functional/constants.py
  theseus/labs/lie_functional/lie_group.py
  theseus/labs/lie_functional/so3.py
  theseus/labs/lie_functional/utils.py
Labels: CLA Signed

#436 Remove nox dependency
  .circleci/config.yml
  .pre-commit-config.yaml
  noxfile.py
  requirements/dev.txt
  tests/geometry/test_point_types.py
Labels: CLA Signed

#435 Bumped version to 0.1.4.
  README.md
  docs/source/getting-started.rst
  setup.py
  theseus/__init__.py
Labels: CLA Signed

#434 This adds support for detaching the hessian contribution to `A_grad` in the sparse solvers
  tests/optimizer/nonlinear/test_backwards.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/cholmod_sparse_autograd.py
  theseus/optimizer/autograd/common.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/cholmod_sparse_solver.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/sparse_linearization.py
Labels: CLA Signed

#425 Detach the derivative though the Hessian
  examples/backward_modes.py
  tests/optimizer/nonlinear/common.py
  tests/optimizer/nonlinear/test_backwards.py
  theseus/optimizer/autograd/baspacho_sparse_autograd.py
  theseus/optimizer/autograd/cholmod_sparse_autograd.py
  theseus/optimizer/autograd/common.py
  theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
  theseus/optimizer/dense_linearization.py
  theseus/optimizer/linear/baspacho_sparse_solver.py
  theseus/optimizer/linear/cholmod_sparse_solver.py
  theseus/optimizer/linear/lu_cuda_sparse_solver.py
  theseus/optimizer/linearization.py
  theseus/optimizer/nonlinear/nonlinear_optimizer.py
  theseus/optimizer/sparse_linearization.py
  theseus/utils/__init__.py
  theseus/utils/utils.py
Labels: CLA Signed

#447 Using resource_class:xlarge for complex CPU unit tests in CI.
  .circleci/config.yml
Labels: CLA Signed

#448 Fixed error that was preventing requirements versions to be used in setup
  requirements/main.txt
  setup.py
Labels: CLA Signed

#453 Update to isort 5.11.5 in precommit.
  .pre-commit-config.yaml
Labels: CLA Signed
